### ISSUE TITLE
Status of slicer library

### ISSUE THREAD

**Issue by Evil-Spirit** [gradientspace/gsSlicerApps#1]
Is this ready for using, or just a prototype?
I've used it for tube_adapter.obj
![gsslicer debugging - microsoft visual studio 2018-01-16 11 11 26](https://user-images.githubusercontent.com/1980537/34971570-07084046-faae-11e7-8927-aea270b08d11.png)

**Comment by rms80** [comment]
I rewrote the core polygon-filler subsystem recently, and you found a case I hadn't hit yet (no automated regression testing, yet)

I would say...it's suitable if you want to experiment. I use it regularly. But it's not a replacement for your existing printing software, yet. Doesn't do support, for example. 

If you want to keep trying, I would suggest using the stable_nov2017 branch I just pushed. It's up to date except for the new polygon-filler (which is currently more robust geometrically, but slower, and doesn't filter out over-printing as well)

**Comment by Evil-Spirit** [comment]
Cool. I was intended to create slicer from a scracth, but found your project and this is good for starting from! btw my project http://notecad.xyz is progressing.

**Comment by rms80** [comment]
you are using g3sharp as well, right? and you have these working in unity-webgl? Are you using .net 3.5 or 4? (I have tried web builds of my own projects but have had no luck yet, I thought it might be because I am using the beta runtime...)

**Comment by Evil-Spirit** [comment]
No, I am currently not using any of your projects. Just wanted to start using slicer.

**Comment by Evil-Spirit** [comment]
@rms80 are you fixed this?

**Comment by rms80** [comment]
yes

**Comment by Evil-Spirit** [comment]
@rms80 thank you!
