### ISSUE TITLE
build failed at gsSlicer?

### ISSUE THREAD

**Issue by samyuchao** [gradientspace/gsSlicerApps#2]
1>------ Build started: Project: gsSlicer, Configuration: Debug Any CPU ------
1>C:\Users\yc\Downloads\gsSlicer\gsSlicer\generators\ThreeAxisPrintGenerator.cs(337,7,337,25): error CS0103: The name 'fill_solid_regions' does not exist in the current context
1>C:\Users\yc\Downloads\gsSlicer\gsSlicer\generators\ThreeAxisPrintGenerator.cs(430,48,430,69): error CS0246: The type or namespace name 'DenseLinesFillPolygon' could not be found (are you missing a using directive or an assembly reference?)

**Comment by rms80** [comment]
should be fixed now. at least, should compile. But you probably need to muck around in SliceViewerMain.cs to get it to do anything...
